sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: We4dJHYFjG6D4m62uBEO/CgVjnhY+TxyyoOJNfal4B6GT2N3g7iT3qXoymcGppLT7A6+Vp7RXMYUsQPLFBqrUFnTHDWK0t1cdfsqJ58U/paGLX+yOVdz7geR4/BblAIA+oLGtvdU6M7hONl4rge84VGQriT0tBOG6GLwt7Cg/eYFT2MTmN5BmJOoZUhRSvbdkED9pNOidi0zZlwm3ALRWBCgWDZe6eN6WwlK6HfVW9+32uSVIce9KdyvgksNlSg79q80/BI/0Sto3Gab0+Nf+jdoMhwt8UEcn9F2A9JSrZWqlEmK2M5mw4auCYXfTdBUdwb4H7lz3FFFqJk5SyMdFQbih2pzMgG8CeROFtuA3jegJ2JLp1zJcbRNqMddR0GZAnSmNs+0cpjisqD4dqKUvrI0Iy/aB3krVEVFhqmLQsdaZvW5aJYyMVZFPV2AcgwbD9oqDIV4FVhNQSFTvNS8+WOMEglFClS6AoVdq1hwqc693gNWSVWPDvEKC7MQwLI05g0R6tq4KuaHbYOe1sadNhAgVroE+IvyylFtQmeYZ9WCeCjz4wB1u9KtE33JEVyondFTqdtX/cH3I3ZjlrHGXS7OKavH1k1tecS8/rPvRbNxNsfY6OfI33wwNmNc3z00MAyN2a64qUnetfR3kBfLKecLA7v8JwcUC3/oXy42HuU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Albert-N-Yanza-Great-Basin-of-the-Nile-And-Explorations-of-the-Nile-Sources_3668
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy